-- 1. Tabla para velas históricas (El "Training Set")
-- Guardamos OHLCV (Open, High, Low, Close, Volume)
-- Esta tabla será la fuente de verdad para entrenar la red neuronal.

create table public.market_candles (
  id bigint generated by default as identity primary key,
  symbol text not null,       -- Ej: 'BTCUSDT'
  timeframe text not null,    -- Ej: '15m', '1h', '4h'
  open float not null,
  high float not null,
  low float not null,
  close float not null,
  volume float not null,
  timestamp bigint not null,  -- Unix Timestamp (ms)
  
  -- Restricción para no duplicar velas
  constraint market_candles_unique unique (symbol, timeframe, timestamp)
);

-- 2. Índices para velocidad
-- Importante para que el entrenamiento no tarde horas en leer los datos.
create index idx_candles_sym_time on public.market_candles (symbol, timeframe, timestamp desc);

-- 3. (Opcional) Tabla para guardar predicciones futuras y validar el modelo
create table public.model_predictions (
  id bigint generated by default as identity primary key,
  symbol text not null,
  predicted_price float not null,
  prediction_time bigint not null,
  actual_outcome float, -- Se llena después para medir accuracy 
  model_version text default 'v1'
);
